# Starter pipeline


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    sudo apt-get install openjdk-8-jdk-headless
    
    echo compiling...
    javac uuuu.Password.java
    echo running...
    java Password
  displayName: 'Run a multi-line script'

