# Starter pipeline

trigger:
- master
steps:
# Linux
- bash: |
    sudo apt-get install openjdk-8-jdk-headless -y
  condition: eq( variables['Agent.OS'], 'Linux' )
  displayName: install jdk for linux
# macOS
- bash: |
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew tap homebrew/cask-versions
    brew update
    brew tap adoptopenjdk/openjdk
    brew cask install adoptopenjdk8
  condition: eq( variables['Agent.OS'], 'Darwin' )
  displayName: install jdk for macos
# Windows
- powershell: |
    echo hopefuly java is already installed
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: hopefully java is installed
 
pool:
  vmImage: 'ubuntu-latest'

steps:
- script: sudo apt-get install openjdk-8-jdk-headless -y
  displayName: 'install jdk8'

- script: |
    echo compiling...
    javac ActualJournal.java
    javac AdditionAndSubsctraction.java
    javac Col.java
    javac Password.java
    javac ServerClient.java
    javac Stopwatch.java
    javac Tip.java
    javac TwoChat.java
    javac WordRandomizer.java
    javac client.java
    echo done compiling!
  displayName: 'Compile'

