# Starter pipeline

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.14'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
- script: sudo apt-get install openjdk-8-jdk-headless -y
  displayName: 'install jdk8'

- script: |
    echo compiling...
    javac ActualJournal.java
    javac AdditionAndSubsctraction.java
    javac Col.java
    javac Password.java
    javac ServerClient.java
    javac Stopwatch.java
    javac Tip.java
    javac TwoChat.java
    javac WordRandomizer.java
    javac client.java
    echo done compiling!
  displayName: 'Compile'

