#  READ THIS
# since java is run write once, run anywhare (WORA) if it compiles on inux it compiles everywhere
# if there is a problem in the code, that program shouldnt compile

trigger:
- master
 
pool:
  vmImage: 'ubuntu-latest'

steps:
- script: sudo apt-get install openjdk-8-jdk-headless -y
  displayName: 'install jdk8'

- script: |
    echo compiling...
    javac ActualJournal.java
    javac AdditionAndSubsctraction.java
    javac Col.java
    javac Password.java
    javac EchoServer.java
    javac Stopwatch.java
    javac Tip.java
    javac OhnoChat.java
    javac WordRandomizer.java
    javac Serverr.java
    echo done compiling!
  failOnStderr: true
  displayName: 'Compile'

